swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Petstore (Simple)
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://helloreverb.com/terms/
  contact:
    $ref: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_simple/petstore_simple.yml#info/contact"
  license:
    $ref#license: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_simple/petstore_simple.yml#info/license"
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref#pets: "./paths/pets.yml"
  $ref#pets-id: "./paths/pets-id.yml"
definitions:
  $ref#pets: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_simple/definitions/pets.yaml"
  $ref#error: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_simple/definitions/error.yaml"
