---
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    #### Echos back every URL, method, parameter and header
    Feel free to make a path or an operation and use **Try Operation** to test it. The echo server will
    render back everything.
schemes:
  - http
host: mazimi-prod.apigee.net
basePath: /echo
paths:
  /:
    get:
      responses:
        $ref: "./responses.yaml#/components/root/get"
    post:
      responses:
        $ref: "./responses.yaml#/components/root/post"
      parameters:
        - $ref: "./name.yaml"
        - $ref: "./year.yaml"
  /test-path/{id}:
    parameters:
      - $ref: "./id.yaml"
    get:
      responses:
        $ref: "./responses.yaml#/components/test-path"
