swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Petstore (Simple)
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://helloreverb.com/terms/
  contact:
    $ref: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_domain/petstore_simple.yaml#info/contact"
  license:
    $ref: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_domain/petstore_simple.yaml#info/license"
host: petstore.swagger.io
basePath: /api
schemes:
  $ref: "https://raw.githubusercontent.com/WindomZ/swagger-merger/dev/example/petstore_domain/petstore_simple.yaml#schemes"
consumes:
  - application/json
produces:
  - application/json
paths:
  $ref: "./paths/index.yaml"
definitions:
  $ref: "./definitions/index.yaml"
